import { randomBytes } from 'node:crypto'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')
const envFilePath = path.join(projectRoot, '.env.local')
const dataDirPath = path.join(projectRoot, '.data')
const force = process.argv.includes('--force')

if (existsSync(envFilePath) && !force) {
  console.log(
    `.env.local already exists at ${envFilePath}. Re-run with --force to replace it.`,
  )
  process.exit(0)
}

mkdirSync(dataDirPath, { recursive: true })

const envLines = [
  '# Generated by pnpm setup:env',
  'PORT=3000',
  'BETTER_AUTH_URL=http://localhost:3000',
  'DATABASE_URL=./.data/drivecellar.db',
  `BETTER_AUTH_SECRET=${randomBytes(48).toString('hex')}`,
  `CONNECTION_ENCRYPTION_KEY=${randomBytes(32).toString('hex')}`,
  '',
]

writeFileSync(envFilePath, envLines.join('\n'), 'utf8')

console.log(`Wrote ${envFilePath}`)
console.log('Next steps:')
console.log('  1. Start the app with docker compose up --build')
console.log('  2. Open http://localhost:3000')
