/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexingRouteImport } from './routes/indexing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationOrganizationViewRouteImport } from './routes/organization/$organizationView'
import { Route as IndexingCidRouteImport } from './routes/indexing/$cid'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as STokenRouteRouteImport } from './routes/s/$token/route'
import { Route as CIdRouteRouteImport } from './routes/c/$id/route'
import { Route as STokenIndexRouteImport } from './routes/s/$token/index'
import { Route as CIdIndexRouteImport } from './routes/c/$id/index'
import { Route as STokenSplatRouteImport } from './routes/s/$token/$'
import { Route as CIdSplatRouteImport } from './routes/c/$id/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiShareDownloadRouteImport } from './routes/api/share/download'
import { Route as ApiFilesUploadRouteImport } from './routes/api/files/upload'
import { Route as ApiFilesDownloadRouteImport } from './routes/api/files/download'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CIdFileSplatRouteImport } from './routes/c/$id/file/$'

const IndexingRoute = IndexingRouteImport.update({
  id: '/indexing',
  path: '/indexing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationOrganizationViewRoute =
  OrganizationOrganizationViewRouteImport.update({
    id: '/organization/$organizationView',
    path: '/organization/$organizationView',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexingCidRoute = IndexingCidRouteImport.update({
  id: '/$cid',
  path: '/$cid',
  getParentRoute: () => IndexingRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRouteRoute = STokenRouteRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRouteRoute = CIdRouteRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenIndexRoute = STokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => STokenRouteRoute,
} as any)
const CIdIndexRoute = CIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CIdRouteRoute,
} as any)
const STokenSplatRoute = STokenSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => STokenRouteRoute,
} as any)
const CIdSplatRoute = CIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CIdRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShareDownloadRoute = ApiShareDownloadRouteImport.update({
  id: '/api/share/download',
  path: '/api/share/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesUploadRoute = ApiFilesUploadRouteImport.update({
  id: '/api/files/upload',
  path: '/api/files/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesDownloadRoute = ApiFilesDownloadRouteImport.update({
  id: '/api/files/download',
  path: '/api/files/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdFileSplatRoute = CIdFileSplatRouteImport.update({
  id: '/file/$',
  path: '/file/$',
  getParentRoute: () => CIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRouteWithChildren
  '/c/$id': typeof CIdRouteRouteWithChildren
  '/s/$token': typeof STokenRouteRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/indexing/$cid': typeof IndexingCidRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/share/download': typeof ApiShareDownloadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/c/$id/$': typeof CIdSplatRoute
  '/s/$token/$': typeof STokenSplatRoute
  '/c/$id/': typeof CIdIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/c/$id/file/$': typeof CIdFileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/indexing/$cid': typeof IndexingCidRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/share/download': typeof ApiShareDownloadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/c/$id/$': typeof CIdSplatRoute
  '/s/$token/$': typeof STokenSplatRoute
  '/c/$id': typeof CIdIndexRoute
  '/s/$token': typeof STokenIndexRoute
  '/c/$id/file/$': typeof CIdFileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexing': typeof IndexingRouteWithChildren
  '/c/$id': typeof CIdRouteRouteWithChildren
  '/s/$token': typeof STokenRouteRouteWithChildren
  '/account/$accountView': typeof AccountAccountViewRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/indexing/$cid': typeof IndexingCidRoute
  '/organization/$organizationView': typeof OrganizationOrganizationViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/download': typeof ApiFilesDownloadRoute
  '/api/files/upload': typeof ApiFilesUploadRoute
  '/api/share/download': typeof ApiShareDownloadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/c/$id/$': typeof CIdSplatRoute
  '/s/$token/$': typeof STokenSplatRoute
  '/c/$id/': typeof CIdIndexRoute
  '/s/$token/': typeof STokenIndexRoute
  '/c/$id/file/$': typeof CIdFileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/indexing'
    | '/c/$id'
    | '/s/$token'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/indexing/$cid'
    | '/organization/$organizationView'
    | '/api/auth/$'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/share/download'
    | '/api/trpc/$'
    | '/c/$id/$'
    | '/s/$token/$'
    | '/c/$id/'
    | '/s/$token/'
    | '/c/$id/file/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/indexing'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/indexing/$cid'
    | '/organization/$organizationView'
    | '/api/auth/$'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/share/download'
    | '/api/trpc/$'
    | '/c/$id/$'
    | '/s/$token/$'
    | '/c/$id'
    | '/s/$token'
    | '/c/$id/file/$'
  id:
    | '__root__'
    | '/'
    | '/indexing'
    | '/c/$id'
    | '/s/$token'
    | '/account/$accountView'
    | '/auth/$authView'
    | '/indexing/$cid'
    | '/organization/$organizationView'
    | '/api/auth/$'
    | '/api/files/download'
    | '/api/files/upload'
    | '/api/share/download'
    | '/api/trpc/$'
    | '/c/$id/$'
    | '/s/$token/$'
    | '/c/$id/'
    | '/s/$token/'
    | '/c/$id/file/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexingRoute: typeof IndexingRouteWithChildren
  CIdRouteRoute: typeof CIdRouteRouteWithChildren
  STokenRouteRoute: typeof STokenRouteRouteWithChildren
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  OrganizationOrganizationViewRoute: typeof OrganizationOrganizationViewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesDownloadRoute: typeof ApiFilesDownloadRoute
  ApiFilesUploadRoute: typeof ApiFilesUploadRoute
  ApiShareDownloadRoute: typeof ApiShareDownloadRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indexing': {
      id: '/indexing'
      path: '/indexing'
      fullPath: '/indexing'
      preLoaderRoute: typeof IndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/$organizationView': {
      id: '/organization/$organizationView'
      path: '/organization/$organizationView'
      fullPath: '/organization/$organizationView'
      preLoaderRoute: typeof OrganizationOrganizationViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indexing/$cid': {
      id: '/indexing/$cid'
      path: '/$cid'
      fullPath: '/indexing/$cid'
      preLoaderRoute: typeof IndexingCidRouteImport
      parentRoute: typeof IndexingRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token/': {
      id: '/s/$token/'
      path: '/'
      fullPath: '/s/$token/'
      preLoaderRoute: typeof STokenIndexRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/c/$id/': {
      id: '/c/$id/'
      path: '/'
      fullPath: '/c/$id/'
      preLoaderRoute: typeof CIdIndexRouteImport
      parentRoute: typeof CIdRouteRoute
    }
    '/s/$token/$': {
      id: '/s/$token/$'
      path: '/$'
      fullPath: '/s/$token/$'
      preLoaderRoute: typeof STokenSplatRouteImport
      parentRoute: typeof STokenRouteRoute
    }
    '/c/$id/$': {
      id: '/c/$id/$'
      path: '/$'
      fullPath: '/c/$id/$'
      preLoaderRoute: typeof CIdSplatRouteImport
      parentRoute: typeof CIdRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/share/download': {
      id: '/api/share/download'
      path: '/api/share/download'
      fullPath: '/api/share/download'
      preLoaderRoute: typeof ApiShareDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/upload': {
      id: '/api/files/upload'
      path: '/api/files/upload'
      fullPath: '/api/files/upload'
      preLoaderRoute: typeof ApiFilesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/download': {
      id: '/api/files/download'
      path: '/api/files/download'
      fullPath: '/api/files/download'
      preLoaderRoute: typeof ApiFilesDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id/file/$': {
      id: '/c/$id/file/$'
      path: '/file/$'
      fullPath: '/c/$id/file/$'
      preLoaderRoute: typeof CIdFileSplatRouteImport
      parentRoute: typeof CIdRouteRoute
    }
  }
}

interface IndexingRouteChildren {
  IndexingCidRoute: typeof IndexingCidRoute
}

const IndexingRouteChildren: IndexingRouteChildren = {
  IndexingCidRoute: IndexingCidRoute,
}

const IndexingRouteWithChildren = IndexingRoute._addFileChildren(
  IndexingRouteChildren,
)

interface CIdRouteRouteChildren {
  CIdSplatRoute: typeof CIdSplatRoute
  CIdIndexRoute: typeof CIdIndexRoute
  CIdFileSplatRoute: typeof CIdFileSplatRoute
}

const CIdRouteRouteChildren: CIdRouteRouteChildren = {
  CIdSplatRoute: CIdSplatRoute,
  CIdIndexRoute: CIdIndexRoute,
  CIdFileSplatRoute: CIdFileSplatRoute,
}

const CIdRouteRouteWithChildren = CIdRouteRoute._addFileChildren(
  CIdRouteRouteChildren,
)

interface STokenRouteRouteChildren {
  STokenSplatRoute: typeof STokenSplatRoute
  STokenIndexRoute: typeof STokenIndexRoute
}

const STokenRouteRouteChildren: STokenRouteRouteChildren = {
  STokenSplatRoute: STokenSplatRoute,
  STokenIndexRoute: STokenIndexRoute,
}

const STokenRouteRouteWithChildren = STokenRouteRoute._addFileChildren(
  STokenRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexingRoute: IndexingRouteWithChildren,
  CIdRouteRoute: CIdRouteRouteWithChildren,
  STokenRouteRoute: STokenRouteRouteWithChildren,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  OrganizationOrganizationViewRoute: OrganizationOrganizationViewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesDownloadRoute: ApiFilesDownloadRoute,
  ApiFilesUploadRoute: ApiFilesUploadRoute,
  ApiShareDownloadRoute: ApiShareDownloadRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
